import './global.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

//import SmoothScroll from './components/smooth-scroll'
import Header from './components/layout/header'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
